USE [master]
GO
/****** Object:  Database [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF]    Script Date: 11/09/2024 7:59:33 AM ******/
CREATE DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UTRDB', FILENAME = N'UTRDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UTRDB_log', FILENAME = N'UTRDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET ARITHABORT OFF 
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET  DISABLE_BROKER 
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET  MULTI_USER 
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET DB_CHAINING OFF 
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET QUERY_STORE = OFF
GO
USE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 11/09/2024 7:59:34 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ConvenienceStoreItems]    Script Date: 11/09/2024 7:59:34 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ConvenienceStoreItems](
	[ItemId] [int] IDENTITY(1,1) NOT NULL,
	[ItemName] [nvarchar](max) NOT NULL,
	[ItemDescription] [nvarchar](max) NOT NULL,
	[ItemImage] [nvarchar](max) NOT NULL,
	[ItemCost] [decimal](10, 2) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Customer]    Script Date: 11/09/2024 7:59:34 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customer](
	[cusID] [int] IDENTITY(1,1) NOT NULL,
	[firstName] [varchar](50) NOT NULL,
	[lastName] [varchar](50) NOT NULL,
	[email] [varchar](100) NOT NULL,
	[pass] [varchar](150) NOT NULL,
	[cardName] [varchar](100) NULL,
	[cardNum] [int] NULL,
	[cardDate] [date] NULL,
 CONSTRAINT [Customer_pk] PRIMARY KEY CLUSTERED 
(
	[cusID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Customers]    Script Date: 11/09/2024 7:59:34 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customers](
	[CusID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](max) NOT NULL,
	[LastName] [nvarchar](max) NOT NULL,
	[Email] [nvarchar](max) NOT NULL,
	[Pass] [nvarchar](max) NOT NULL,
	[CardName] [nvarchar](max) NOT NULL,
	[CardNum] [int] NULL,
	[CardDate] [datetime2](7) NULL,
 CONSTRAINT [PK_Customers] PRIMARY KEY CLUSTERED 
(
	[CusID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Fuel]    Script Date: 11/09/2024 7:59:34 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Fuel](
	[fuelID] [int] IDENTITY(1,1) NOT NULL,
	[storeID] [int] NULL,
	[fuelType] [varchar](50) NOT NULL,
	[pricePL] [float] NOT NULL,
 CONSTRAINT [Fuel_pk] PRIMARY KEY CLUSTERED 
(
	[fuelID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Manager]    Script Date: 11/09/2024 7:59:34 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Manager](
	[userID] [int] IDENTITY(1,1) NOT NULL,
	[storeID] [int] NULL,
	[firstName] [varchar](50) NOT NULL,
	[lastName] [varchar](50) NOT NULL,
	[email] [varchar](100) NOT NULL,
	[pass] [varchar](150) NOT NULL,
 CONSTRAINT [Manager_pk] PRIMARY KEY CLUSTERED 
(
	[userID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Store]    Script Date: 11/09/2024 7:59:34 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Store](
	[storeID] [int] IDENTITY(1,1) NOT NULL,
	[outlet] [varchar](50) NULL,
	[suburb] [varchar](50) NOT NULL,
	[street] [varchar](50) NOT NULL,
	[streetNum] [varchar](10) NOT NULL,
	[postcode] [int] NOT NULL,
 CONSTRAINT [Store_pk] PRIMARY KEY CLUSTERED 
(
	[storeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Fuel]  WITH CHECK ADD  CONSTRAINT [Fuel_fk] FOREIGN KEY([storeID])
REFERENCES [dbo].[Store] ([storeID])
GO
ALTER TABLE [dbo].[Fuel] CHECK CONSTRAINT [Fuel_fk]
GO
ALTER TABLE [dbo].[Manager]  WITH CHECK ADD  CONSTRAINT [Manager_fk] FOREIGN KEY([storeID])
REFERENCES [dbo].[Store] ([storeID])
GO
ALTER TABLE [dbo].[Manager] CHECK CONSTRAINT [Manager_fk]
GO
USE [master]
GO
ALTER DATABASE [C:\USERS\COSTA\ONEDRIVE\DOCUMENTS\01 - UNIVERSITY\2024\STUDIO\UTR\WEBAPPLICATION3\WEBAPPLICATION3\APP_DATA\UTRDB.MDF] SET  READ_WRITE 
GO
